apiVersion: apps/v1
kind: Deployment
metadata: 
    name: httpd-frontend
spec: 
    replicas: 3
    selector:
        matchLabels:
          type: front-end
    template:
      metadata: 
        name: myapp-pod
        labels: 
          app: myapp
          type: front-end
      spec:
        containers:
          - name: http-pod
            image: httpd:2.4-alpine
       